[tool.poetry]
name = "discord-bot"
version = "1.3.4"
description = "This is a discord bot (the impostor)"
authors = ["Baz"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
flask = "^1.1.2"
replit = "^2.0.0"
dblpy = "^0.4.0"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
